### ISSUE TITLE
Question about keyword.py

### ISSUE THREAD

**Issue by gmichalo** [neulab/guided_summarization#21]
I was wondering why you separate the keywords with the word [SEP]?
```
out.write(' [SEP] '.join(new_words)+'\n')
```
I am mostly asking because if I am understanding the code correctly the [SEP] is between any two keywords and not keywords from different sentences.

**Comment by zdou0830** [comment]
Hi, your understanding is correct and it's just a heuristic. Maybe inserting [SEP] between keywords from different sentences would be better but we didn't try other strategies.
