### ISSUE TITLE
In terms of the released model for cnndm datsets

### ISSUE THREAD

**Issue by jingunkwon** [neulab/guided_summarization#24]
Hello! I appreciate your sharing this work.

When I used your pre-trained model for cnndm datasets, I obtained the results as follow:

Preparing documents... 0 line(s) ignored
Running ROUGE...

1 ROUGE-1 Average_R: 0.40673 (95%-conf.int. 0.40418 - 0.40929)
1 ROUGE-1 Average_P: 0.55422 (95%-conf.int. 0.55179 - 0.55676)
1 ROUGE-1 Average_F: 0.45788 (95%-conf.int. 0.45563 - 0.46023)

1 ROUGE-2 Average_R: 0.19777 (95%-conf.int. 0.19539 - 0.20017)
1 ROUGE-2 Average_P: 0.26860 (95%-conf.int. 0.26579 - 0.27132)
1 ROUGE-2 Average_F: 0.22213 (95%-conf.int. 0.21968 - 0.22445)

1 ROUGE-L Average_R: 0.37628 (95%-conf.int. 0.37380 - 0.37870)
1 ROUGE-L Average_P: 0.51289 (95%-conf.int. 0.51046 - 0.51537)
1 ROUGE-L Average_F: 0.42369 (95%-conf.int. 0.42153 - 0.42601)

Elapsed time: 158.417 seconds

The scores are slightly lower than the reported scores.
Am I missing something?

Thank you so much again.

**Comment by zdou0830** [comment]
Hello, we did find that because of the differences in files2rouge version (we used b0979655bbc32b65641e69840c88a2aede5e10a2) and ROUGE-1.5.5 installation process, the final ROUGE scores can vary (usually within 0.2 points).

**Comment by jingunkwon** [comment]
I appreciate your reply!!
Thank you so much!!
