### ISSUE TITLE
Questions about implementation

### ISSUE THREAD

**Issue by danieldeutsch** [neulab/guided_summarization#25]
Hi, thanks for the interesting paper and for releasing your code. I have a couple of questions about the implementation.

1. I see that you got the input data from the [sensim](https://github.com/icml-2020-nlp/semsim) repo and you released the oracle sentences [here](https://drive.google.com/file/d/12SpWwfD3syIxcC-SdSNnDOI5sbXJaylC/view). How did you sentence-split the input data to generate the oracle sentences?

2. When the documents and sentence guidance signals are passed to the BART model, you say that they should not be tokenized. Does that also mean it should not be sentence tokenized (i.e., the `<q>` should be removed)?

3. Do you have outputs from the models that you can release?

Thanks!

**Comment by zdou0830** [comment]
1. I used nltk (sent_tokenize).
2. I actually forget this detail. I think it may not affect the model much as long as the training/testing settings are consistent.
3. I just found that the outputs are available on ExplainaBoard (http://explainaboard.nlpedia.ai/download/summ.html, https://drive.google.com/drive/folders/1R5ReFS3bmE3baizBzYqQUB6F7zH-O_xk).

**Comment by danieldeutsch** [comment]
Thanks!
