### ISSUE TITLE
How large GPU is expected to train GSum model?

### ISSUE THREAD

**Issue by yfqiu98** [neulab/guided_summarization#27]
Hi, I have noticed in your script that you use 2 GPU with 1024 tokens per each, and keep batch size as the same as bart to train the model. Can I ask what is the memory for your GPU? I use several 16G gpus which can train the bart but not work for GSum.

Thanks

**Comment by zdou0830** [comment]
Hi, we found that for the BART-based models we need GPUs with more than 32GB memory.

**Comment by nargesdel** [comment]
> Hi, we found that for the BART-based models we need GPUs with more than 32GB memory.

@zdou0830 
Hello, thank you very much for your reply. If there are GPUS availabe with 24G memmory, how could we specify the number of GPU? How many GPUs do we need? Do we need to change MAX_TOKENS in z_train.sh? If so what value will work for that?

I highly appreciate your response.
Thanks
