### ISSUE TITLE
请问大佬，在测试时BertAbs 怎么添加BertExt生成的指导信号

### ISSUE THREAD

**Issue by tiexueYL** [neulab/guided_summarization#28]
谢谢您的回复！

**Comment by zdou0830** [comment]
你好，可以直接把data里面的'src_sent_labels'换成BertExt的输出，然后用https://github.com/neulab/guided_summarization/blob/master/bert/highligted_sentence_data.py这个生成数据。或者也可以先用BertExt生成一下输出，再用bert的tokenizer去tokenize一下、用torch.save保存，然后用https://github.com/neulab/guided_summarization/blob/master/bert/example_add_guidance.py这个生成数据。

**Comment by tiexueYL** [comment]
谢谢作者大大回复！！！请问大佬BertExt输出的预测摘要有格式要求吗？谢谢您啦

**Comment by zdou0830** [comment]
就保证最后生成的数据和直接用https://github.com/neulab/guided_summarization/blob/master/bert/highligted_sentence_data.py 生成的数据格式一样就可以了。

**Comment by tiexueYL** [comment]
请问“把data里面的'src_sent_labels'换成BertExt的输出”是这样吗？1.txt是BertExt预测的摘要文件。实在抱歉我太菜了浪费您的时间了
![image](https://user-images.githubusercontent.com/76195456/132663219-165becd3-7d7c-4bf5-aa04-b0b657b508b7.png)

**Comment by zdou0830** [comment]
没有没有。就是'src_sent_labels'要换成[0, 1,..]这样的向量 每个元素对应一句话，1表示选这个句子，0表示不选。

**Comment by tiexueYL** [comment]
> 没有没有。就是'src_sent_labels'要换成[0, 1,..]这样的向量 每个元素对应一句话，1表示选这个句子，0表示不选。

抱歉大佬，我实在是搞不明白了。等您有空的时候可不可以麻烦您帮我远程操作一下呀，有偿，多少钱您说，我的QQ是997924541，麻烦您啦，多谢大佬

**Comment by tiexueYL** [comment]
谢谢您啦！
