### ISSUE TITLE
How to get guidance.pt

### ISSUE THREAD

**Issue by kamalkraj** [neulab/guided_summarization#3]
https://github.com/neulab/guided_summarization/blob/a8956dfe5e77650aae9015bc3c569ef03d224dac/bert/example_add_guidance.py#L13

**Comment by zdou0830** [comment]
Hi, as in README, this is an example of how to add guidance signals into the dataset, and you can extract any guidance signals you want. In the repo, [highligted_sentence_data.py](https://github.com/neulab/guided_summarization/blob/master/bert/highligted_sentence_data.py) shows how we create the highlighted sentence data from the preprocessed data.
