### ISSUE TITLE
Initializing both encoders with pre-trained BART

### ISSUE THREAD

**Issue by fabrahman** [neulab/guided_summarization#31]
Hello, 
thanks for the great work.
I was wondering if you can point me to the part of code where you initialized the first N layers of both encoders with pre-trained BART and the newly added layer randomly. Thank you in advance

**Comment by zdou0830** [comment]
Hello, as in the paper, for BART we initialize the top layers of the two encoders with pretrained parameters and they are separately trained.

https://github.com/neulab/guided_summarization/blob/ea4bbe91f189cdb51f7f6a827210f9adc5319b3c/bart/fairseq/trainer.py#L186-L193

**Comment by fabrahman** [comment]
> Hello, as in the paper, for BART we initialize the top layers of the two encoders with pretrained parameters and they are separately trained.
> 
> https://github.com/neulab/guided_summarization/blob/ea4bbe91f189cdb51f7f6a827210f9adc5319b3c/bart/fairseq/trainer.py#L186-L193

Thanks @zdou0830 for the prompt response. I realized I confused the BART initialization with the BERT one.
In this regard, I am curious to know if you also tried using a single bart encoder and simply concatenate the guidance signals with the document? If yes, how the results were different? Thank you for you comment on this.

**Comment by zdou0830** [comment]
Hi, thanks for the idea. We didn't try this strategy.
