### ISSUE TITLE
about nyt preprocessing!

### ISSUE THREAD

**Issue by jingunkwon** [neulab/guided_summarization#33]
In the paper, you have mentioned you followed the preprocessing step by Kedzie 2018.

Did you concatenate the two gold summaries and dropped words less than 100?

Because I followed it and obtained little bit different scores using BART model.

R-1-F.    R-2-F.    R-L-F
57.75.    38.03.    42.19

The reported scores in your paper are
R-1-F.    R-2-F.    R-L-F
54.13.    35.15.    47.00

I wonder how you preprocess datasets.

Thank you so much!

**Comment by zdou0830** [comment]
Hi, sorry that I've forgotten the details but I think I followed this repo https://github.com/kedz/summarization-datasets.

**Comment by jingunkwon** [comment]
Thank you so much for your reply.
Yes. I also followed it. If we followed the above repo, we obtain two different summaries.
Did you concat them as a one gold summary? or just used the first (long) summary as a gold summary?
Sorry for asking a lot..

**Comment by zdou0830** [comment]
Hi, sorry that right now I'm not sure about this. I think you can check the oracle ROUGE scores and see which one matches our reported scores?

**Comment by jingunkwon** [comment]
Perferct! I forgot to check oracle! Thank you so much!
