### ISSUE TITLE
Would you provide the output file of your models on XSUM and CNNDM

### ISSUE THREAD

**Issue by xwjim** [neulab/guided_summarization#34]

**Comment by zdou0830** [comment]
You can find the output file on CNNDM here https://drive.google.com/drive/folders/1R5ReFS3bmE3baizBzYqQUB6F7zH-O_xk (abs-gsum).

**Comment by xwjim** [comment]
> You can find the output file on CNNDM here https://drive.google.com/drive/folders/1R5ReFS3bmE3baizBzYqQUB6F7zH-O_xk (abs-gsum).

Thanks a lot for your kindness. By the way, Is there a description for each column of the files?

**Comment by zdou0830** [comment]
You can find it here https://github.com/neulab/ExplainaBoard/tree/main/output_format/summ

**Comment by xwjim** [comment]
Thanks a lot
