### ISSUE TITLE
Oracle summary

### ISSUE THREAD

**Issue by kamalkraj** [neulab/guided_summarization#4]
How to generate highlight sentence data for Bart model ?

The one you shared in the Bart folder generated using the below function ?
https://github.com/neulab/guided_summarization/blob/a8956dfe5e77650aae9015bc3c569ef03d224dac/bert/prepro/data_builder.py#L161

**Comment by zdou0830** [comment]
Yes. Note that you'll need to do tokenization and sentence segmentation first on the Bart data.
