### ISSUE TITLE
关于bertext加入guidance的训练

### ISSUE THREAD

**Issue by xtlv426** [neulab/guided_summarization#42]
你好，我正在尝试将你bertExt的部分用于我自己的数据集进行训练，但是加入不同的guidance会得到同样的rouge分数，请问是不是你的代码在Presumm的基础上只改写了abs的部分？如果我直接将z_trainer用到ext上可不可行呢？

**Comment by tiexueYL** [comment]
> 

大佬 请问你是怎么在bertext加指导信号的 求指点！！多谢大佬
