### ISSUE TITLE
Applying multiple guidance signals

### ISSUE THREAD

**Issue by nargesdel** [neulab/guided_summarization#50]
Hello. Thank you very much for sharing the repository and great research.
If I want to use multiple guidance signals, such as, keywords and important sentences at the same time, do I need to use them in the same file 'z'? If so how it could be? I assume that for each data point that are in one line we have a guidance signal in the same line of that datapoint. What if we have two guidance signals? How could I save them in the same line?

Thanks

**Comment by zdou0830** [comment]
Thank you! We didn't try multiple guidance signals but it should be doable. You can put the two signals in the same file and separate them with a special token for each datapoint.

**Comment by nargesdel** [comment]
Thank you for your reply. 

I wanted to use keywords and important sentences as the guidance signals. 

I saw that here important sentences were used as the guidance signal. We have source text in one line in source file. Then, we have important sentences in the corresponding line in guidance file ('z'). If I want to use both keywords and important sentences in guidance file ('z'), they need to be on the same line seperated with special token. Right? 

Also, I need to use special token to separate keywords for each datapoint. Then, in this case I need to use different special token, not to be confused with seperator between guidance signals? Right? I mean I need to have two different separator as special token?

Thank you in advance.

**Comment by zdou0830** [comment]
Correct!

**Comment by nargesdel** [comment]
I appreciate it. Thanks.
