### ISSUE TITLE
highlight sentence data not in order

### ISSUE THREAD

**Issue by nargesdel** [neulab/guided_summarization#51]
Hello,

I have realized that the data available in [this link]([url](https://drive.google.com/file/d/12SpWwfD3syIxcC-SdSNnDOI5sbXJaylC/view?usp=sharing)) is not in order corresponding to each datapoint in dataset. I assumed that each line(data point) in dataset needs to be related to the same line in oracle sentences, but it is not. If so, how to get the ordered data?

Thanks.

**Comment by zdou0830** [comment]
You can reference this file https://github.com/neulab/guided_summarization/blob/master/scripts/sents.py to see how you can get the ordered data.

**Comment by nargesdel** [comment]
@zdou0830 Thank you very much for your reply.
This code is goring to be Oracle sentences. How about sentences for test?
Thanks.

**Comment by zdou0830** [comment]
Hi, during test time, you can arrange the guided sentences in order.
