### ISSUE TITLE
Number of epochs

### ISSUE THREAD

**Issue by nargesdel** [neulab/guided_summarization#52]
Hello!

I am wondering if you could let us know the default number of epochs set to train. I could not find any parameter to set for max_epoch.
Also, is it enough to have max_epoch=10 for CNN DailyMail dataset?

Thank you very much for your consideration.

Bests,

**Comment by zdou0830** [comment]
Hi, for BERT, I trained the model for 200k steps. for BART, I trained the model for 5 epochs.
